### ISSUE TITLE
Adding in an extra list item

### ISSUE THREAD

**Issue by PaulVipond** [deakjahn/huge_listview#1]
Hi, I'd love to use this for my chat app. Could you tell me how I could smoothly animate in an extra list item if a new message appears? I'm also not sure how to scroll the DraggableScrollbarThumb so it keeps pace with the list when you scroll by swiping list items down.

**Comment by deakjahn** [comment]
Well, it depends on `ScrollablePositionedList`, so you would probably need to download that for yourself and modify it...

**Comment by deakjahn** [comment]
> I'm also not sure how to scroll the `DraggableScrollbarThumb`

Well, did I forget to implement this? :-)

**Comment by deakjahn** [comment]
It looks like it was a single call missing (but I changed a few extra lines to rename the function as well). Could you check it out?

**Comment by PaulVipond** [comment]
Wow, that is awesome service thank you :-) The scrollthumb keeps nice pace with the manual scrolling now. I'll also look into the ScrollablePositionedList separately thanks.

I did have one more question: when the list first initialises, my data fetch method is called 10 times for 20 items (page size) each time, so a total of 200 items, out of max 5000. There are only about 12 items showing on screen, so it seems a bit data heavy. Is there any way of tweaking this? Happy to raise as a separate request if you like.

**Comment by deakjahn** [comment]
This should be investigated first. My use case is a dictionary with nearly 100,000 word items. When I start my app and the first page appears, my `loadDictPage()` is actually only called twice. Try to look around in `_initCache()` in `huge_listview.dart`, the 256 should be the constant driving this. The original SO question had 500 there and for a moment, I also thought about making this configurable but it didn't seem important in the end. Maybe it is.

One idea would be to calculate this some other way, maybe not dividing but actually allowing a set number of data pages?

**Comment by PaulVipond** [comment]
Thanks for the info, I'll do some digging and see if I can find out why it's loading so much initially. I agree though, it would be nice to either let it specify the initial cache size, or allow a configurable number of pages.
