### ISSUE TITLE
Lost updates for flutter 3.0

### ISSUE THREAD

**Issue by MohamedRisaldarTA** [deakjahn/huge_listview#12]

**Comment by deakjahn** [comment]
Well, what's exactly the problem? :-)

**Comment by MohamedRisaldarTA** [comment]
> Well, what's exactly the problem? :-)

I think the minimum supported flutter version is now 3.3.
can we still have support for 3.0.5 at least?

**Comment by deakjahn** [comment]
Oh, I see. I was so happy about the new SDK and language features that I was too eager to move forward. I moved all my apps but there's no need with these plugins and packages, you're right...

**Comment by MohamedRisaldarTA** [comment]
Please note that Flutter 3.0 uses dart version 2.17.0

**Comment by deakjahn** [comment]
Then what's your suggestion? Shall we make a breaking change jump to 3.0.0?

**Comment by MohamedRisaldarTA** [comment]
what if we just revert the sdk to start supporting from 2.17.0(https://github.com/deakjahn/huge_listview/commit/8d7336d20d8362d6fde8b2486726d02199176c44#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25)

**Comment by deakjahn** [comment]
I'm not sure what happens when we call it from an SDK 3 app then. All my apps are already at that level, and I suspect quite a few out there, too...

**Comment by MohamedRisaldarTA** [comment]
The stable version of Flutter 3.10.0(Dart 3.0.0) is released just before a few days.
I think it will be better if we can release a latest version for flutter 3.0.0(Dart 2.17.0) before going to flutter 3.10.0(Dart 3.0.0) as many of the users won't keep flutter updated unless required.

**Comment by deakjahn** [comment]
Yep but there were such awaited and coveted changes in Dart now, patterns and records, that I'm sure many of us were eager to switch over. :-) But you're right, there's nothing particular in this package that would require it for now.

I uploaded it now but not yet published. Could you check or test?

**Comment by MohamedRisaldarTA** [comment]
lgtm

**Comment by deakjahn** [comment]
Flutter Publish reports:

```
Package validation found the following hint:
* The declared SDK constraint is '>=2.17.0 <3.0.0', this is interpreted as '>=2.17.0 <4.0.0'.
```

I wonder if we really need to make it so. It kinda looks like having the cake and eating it, too...

**Comment by deakjahn** [comment]
OK, let's hope it's all right like this. Sorry for the disturbance.

**Comment by MohamedRisaldarTA** [comment]
It's fine, Closing this issue.
