### ISSUE TITLE
Flutter 3.0 support, and two buggs

### ISSUE THREAD

**Issue by Ne0n11** [deakjahn/huge_listview#6]
Hello, so, for supporting flutter 3.0 - its about WidgetsBindings are now not nullable, so no need to add "?" at the end.

And about bugs - 1) if list fits to the screen, there is no need to show scrollbar,  2) when scrolling to the very end of list with mouse, it jumps beyond the list, and then goes back.

**Comment by deakjahn** [comment]
See version 2.0.4.
