### ISSUE TITLE
Scrollbar is always visible.

### ISSUE THREAD

**Issue by ikramuldu** [deakjahn/huge_listview#9]
Not hiding while idle.

**Comment by deakjahn** [comment]
This is not the standard scrollbar but a separate one (as described in the README). Considering that you're free to provide your own, I wonder if the package itself should do it automatically. I don't yet know...

**Comment by ikramuldu** [comment]
But the package "draggable_scrollbar" hides scrollbar while idle.

**Comment by deakjahn** [comment]
OK, I'll look into it. This package doesn't depend on `draggable_scrollbar` but uses parts of its source code, so later changes to the scrollbar are not reflected here. But there was no other way to solve what's needed here.

**Comment by deakjahn** [comment]
@ikramuldu Added it. In my tests, it seems to work all right. Please, could you test it? I wouldn't publish it right away without some feedback. :-)

**Comment by ikramuldu** [comment]
Yes, it is working now.

**Comment by deakjahn** [comment]
OK, let's be brave. I'll publish it.
